#!/usr/bin/env bash
set -e

# install code ocean aux tools
mkdir -p /opt
cd /opt
git clone https://github.com/codeocean/co_aux_tools.git
cd co_aux_tools/
git checkout c76c660254091bf2446fce6eda6c4a07ac787e84
chmod +x {g,s}et_*
ln -s $PWD/{g,s}et_*.py /usr/local/bin
